// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using p1_Ap1_RamonUreña.DAL;

#nullable disable

namespace p1_Ap1_RamonUreña.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20251011014501_Existencias")]
    partial class Existencias
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("p1_Ap1_RamonUreña.Models.DetallesHuacales", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdEntrada")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Precio")
                        .HasColumnType("REAL");

                    b.Property<int>("TiposId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetalleId");

                    b.HasIndex("IdEntrada");

                    b.ToTable("DetallesHuacales");
                });

            modelBuilder.Entity("p1_Ap1_RamonUreña.Models.EntradasHuacales", b =>
                {
                    b.Property<int>("IdEntrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<double>("Importe")
                        .HasColumnType("REAL");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdEntrada");

                    b.ToTable("EntradasHuacales");
                });

            modelBuilder.Entity("p1_Ap1_RamonUreña.Models.TiposHuacales", b =>
                {
                    b.Property<int>("TipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoTamano")
                        .HasColumnType("TEXT");

                    b.HasKey("TipoId");

                    b.ToTable("TipoHuacales");

                    b.HasData(
                        new
                        {
                            TipoId = 1,
                            Existencia = 0,
                            TipoColor = "Verde",
                            TipoTamano = "Grande"
                        },
                        new
                        {
                            TipoId = 2,
                            Existencia = 0,
                            TipoColor = "Rojo",
                            TipoTamano = "Grande"
                        });
                });

            modelBuilder.Entity("p1_Ap1_RamonUreña.Models.DetallesHuacales", b =>
                {
                    b.HasOne("p1_Ap1_RamonUreña.Models.EntradasHuacales", null)
                        .WithMany("DetallesHuacales")
                        .HasForeignKey("IdEntrada")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("p1_Ap1_RamonUreña.Models.EntradasHuacales", b =>
                {
                    b.Navigation("DetallesHuacales");
                });
#pragma warning restore 612, 618
        }
    }
}
